/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package loginingfilegui;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UIDefaults;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import static loginingfilegui.MainFrameGUI.check;
import static loginingfilegui.MainFrameGUI.rnd;

/**
 *
 * @author nazarov
 */
public class MainjPanelToGraphics extends javax.swing.JPanel {

    /**
     * Creates new form MainjPanelToGraphics
     */
    public MainjPanelToGraphics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                
        // Цвет фона окнас логами
        Color bgColor = Color.BLACK;
        UIDefaults defaults = new UIDefaults();
        defaults.put("EditorPane[Enabled].backgroundPainter", bgColor);
        jTextPane1.putClientProperty("Nimbus.Overrides", defaults);
        jTextPane1.putClientProperty("Nimbus.Overrides.InheritDefaults", true);
        jTextPane1.setBackground(bgColor);
        
       StyledDocument doc = jTextPane1.getStyledDocument();
        String fPath = "";
        JFileChooser fileopen = new JFileChooser(System.getProperty("user.dir"));
        int ret = fileopen.showDialog(null, "Чтение файла с данными");
        if (ret == JFileChooser.APPROVE_OPTION) {
            File file = fileopen.getSelectedFile();
            fPath = file.getPath();
        }
         try {
     // FileReader textFileReader = new FileReader(fPath);
      InputStreamReader inputsream = new InputStreamReader(new FileInputStream(fPath), "UTF8"); // Правильное отображение русскаого языка чтение буыера такое себе
      BufferedReader bufReader = new BufferedReader(inputsream);
     // BufferedReader bufReader = new BufferedReader(new InputStreamReader(
      //                new FileInputStream(fPath), "UTF8"));
      
      char[] buffer = new char[8096];
      int numberOfCharsRead = bufReader.read(buffer); // read will be from
      // memory
      int tmpColor = 1;
      while (numberOfCharsRead != -1) {
         System.out.println(tmpColor);
         Color clr2 = new Color(200, 255, 0);  // не вариант это использовать красит весл текст
         Color clr3 = new Color(225, 200, 0);  // не вариант это использовать красит весл текст
        String strTmp = String.valueOf(buffer, 0, numberOfCharsRead);
        String[] tmpSplitStr = strTmp.split("\n");
        System.out.println(tmpSplitStr.length);
        for (int i=0; i<tmpSplitStr.length; ++i){ // это просто понять что там выходит
           String[] podstroki = tmpSplitStr[i].split("\t"); // Создаем подстроки уже табом.
           for(String n : podstroki){
             System.out.println(n);
        //тут пробуем добавлять текст цветом
        SimpleAttributeSet pink = new SimpleAttributeSet();
       // StyleConstants.setForeground(pink, Color.pink); 
         StyleConstants.setForeground(pink, new Color(rnd(255), rnd(255), rnd(255))); 
        try
        {
             // тут нужно сделать отдельную функцию для переборазначений и цветов под них пока так
              if (check(n) == 1) { // передам в функцию для проверки пока одного значения
             doc.insertString(doc.getLength(), n + " ", pink);}
              else doc.insertString(doc.getLength(), n + " ", null); // так вносим с определенным стилем
        }
        catch(Exception e) { System.out.println(e); }
           }
             try {
                 doc.insertString(doc.getLength(), "\n ", null); // так просто новая строка
             } catch (BadLocationException ex) {
                 Logger.getLogger(MainFrameGUI.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        numberOfCharsRead = inputsream.read(buffer);
       
        jTextPane1.setStyledDocument(doc);  // тут мы апрсто засовываем сформированный документ
        
        /* // Старая конструкция тестовая пробовал разное
        jTextPane1.setContentType("text/html");
        jTextPane1.setEditable(false);

        jTextPane1.setForeground(clr2);
        //jTextPane1.setText("<a href=\"abc\">" + strTmp + "</a>" + "\n" + "Строка  <b>слово</b>" + "\n" +   "<hr color=\"red\" width=\"300\">"); // это работает
        jTextPane1.setText(strTmp + "</a>" + "\n" + "Строка  <b>слово</b>"); // это работает
        */
        //if (tmpColor <=255){
        ++tmpColor;//}
      }

      bufReader.close();

    } catch (IOException e) {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
  


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
